SN---<:SN:>
SuE---<:SuE:>
hgf_isbn---<:hgf_isbn:>
hgf_rn---<:hgf_rn:>
hgf_propnr---<:hgf_propnr:>
hgf_repnr---<:hgf_repnr:>
hgf_author---<:hgf_author:>
hgf_gender---<:hgf_gender:>
hgf_institut---<:hgf_institut:>
hgf_okinst---<:hgf_okinst:>
hgf_maininst---<:hgf_maininst:>
hgf_okzb---<:hgf_okzb:>
hgf_last---<:hgf_last:>
hgf_bereich---<:hgf_bereich:>
hgf_confname---<:hgf_confname:>
hgf_confcity---<:hgf_confcity:>
hgf_confacro---<:hgf_confacro:>
hgf_confland---<:hgf_confland:>
hgf_title---<:hgf_title:>
hgf_littit---<:hgf_littit:>
hgf_lithsv_a---<:hgf_lithsv_a:>
hgf_lithsv_b---<:hgf_lithsv_b:>
hgf_lithsv_c---<:hgf_lithsv_c:>
hgf_pub---<:hgf_pub:>
hgf_pubcity---<:hgf_pubcity:>
hgf_pubyear---<:hgf_pubyear:>
hgf_pages---<:hgf_pages:>
hgf_confedate---<:dd:>/<:mm:>/<:year:>
hgf_confsdate---<:dd:>/<:mm:>/<:year:>
hgf_edate---<:dd:>/<:mm:>/<:year:>
hgf_sdate---<:dd:>/<:mm:>/<:year:>
hgf_abstract---<:hgf_abstract:>
hgf_edition---<:hgf_edition:>
hgf_titbook---<:hgf_titbook:>
hgf_titseries---<:hgf_titseries:>
hgf_journal---<:hgf_journal:>
hgf_jourtit---<:hgf_jourtit:>
hgf_jouryear---<:hgf_jouryear:>
hgf_volpage---<:hgf_volpage:>
hgf_volpagec---<:hgf_volpagec:>
hgf_keyword---<:hgf_keyword:>
hgf_enrich---<:hgf_enrich:>
hgf_volume---<:hgf_volume:>
hgf_issn---<:hgf_issn:>
hgf_issue---<:hgf_issue:>
hgf_editor---<:hgf_editor:>
hgf_lafa---<:hgf_lafa:>
hgf_comment---<:hgf_comment:>
hgf_webyear---<:hgf_webyear:>
hgf_autype---<:hgf_autype:>
hgf_support---<:hgf_support:>
hgf_intno---<:hgf_intno:>
hgf_groups---<:hgf_groups:>
hgf_doi---<:hgf_doi:>
hgf_zdbid---<:hgf_zdbid:>
hgf_uni---<:hgf_uni:>
hgf_handle---<:hgf_handle:>
hgf_uri---<:hgf_uri:>
hgf_urn---<:hgf_urn:>
hgf_isi---<:hgf_isi:>
hgf_scopus---<:hgf_scopus:>
hgf_file_RENAMED---<:hgf_file_RENAMED:>
hgf_coll---<:hgf_coll:>
hgf_abstract---<:hgf_abstract:>
hgf_thesis---<:hgf_thesis:>
hgf_report---<:hgf_report:>
hgf_talk---<:hgf_talk:>
hgf_conf---<:hgf_conf:>
hgf_book---<:hgf_book:>
hgf_jourart---<:hgf_jourart:>
hgf_unpub---<:hgf_unpub:>
hgf_patent---<:hgf_patent:>
hgf_other---<:hgf_other:>
rn_minutes---<:rn_minutes:>
rn_intrep---<:rn_intrep:>
rn_report---<:rn_report:>
rn_preprint---<:rn_preprint:>
rn_course---<:rn_course:>
rn_bachelor---<:rn_bachelor:>
rn_diploma---<:rn_diploma:>
rn_master---<:rn_master:>
rn_exam---<:rn_exam:>
rn_magister---<:rn_magister:>
rn_phd---<:rn_phd:>
rn_habil---<:rn_habil:>
rn_talk---<:rn_talk:>
rn_lecture---<:rn_lecture:>
rn_poster---<:rn_poster:>
rn_images---<:rn_images:>
rn_conf---<:rn_conf:>
rn_book---<:rn_book:>
rn_proc---<:rn_proc:>
rn_contb---<:rn_contb:>
rn_refs---<:rn_refs:>
rn_journal---<:rn_journal:>
rn_contrib---<:rn_contrib:>
rn_patent---<:rn_patent:>
rn_abstract---<:rn_abstract:>
rn_comm---<:rn_comm:>
rn_formtmp---<:rn_formtmp:>
rn_news---<:rn_news:>
rn_notes---<:rn_notes:>
rn_project---<:rn_project:>
rn_event---<:rn_event:>
rn_dataset---<:rn_dataset:>
rn_sware---<:rn_sware:>
rn_physobj---<:rn_physobj:>
rn_media---<:rn_media:>
mrn_minutes---<:rn_minutes:>
mrn_intrep---<:mrn_intrep:>
mrn_report---<:mrn_report:>
mrn_preprint---<:mrn_preprint:>
mrn_course---<:mrn_course:>
mrn_bachelor---<:mrn_bachelor:>
mrn_diploma---<:mrn_diploma:>
mrn_master---<:mrn_master:>
mrn_exam---<:mrn_exam:>
mrn_magister---<:mrn_magister:>
mrn_phd---<:mrn_phd:>
mrn_habil---<:mrn_habil:>
mrn_talk---<:mrn_talk:>
mrn_lecture---<:mrn_lecture:>
mrn_poster---<:mrn_poster:>
mrn_images---<:mrn_images:>
mrn_conf---<:mrn_conf:>
mrn_book---<:mrn_book:>
mrn_proc---<:mrn_proc:>
mrn_contb---<:mrn_contb:>
mrn_refs---<:mrn_refs:>
mrn_journal---<:mrn_journal:>
mrn_contrib---<:mrn_contrib:>
mrn_patent---<:mrn_patent:>
mrn_abstract---<:mrn_abstract:>
mrn_comm---<:mrn_comm:>
mrn_formtmp---<:mrn_formtmp:>
mrn_news---<:mrn_news:>
mrn_notes---<:mrn_notes:>
mrn_project---<:mrn_project:>
mrn_event---<:mrn_event:>
mrn_dataset---<:mrn_dataset:>
mrn_sware---<:mrn_sware:>
mrn_physobj---<:mrn_physobj:>
mrn_media---<:mrn_media:>
col_minutes---<:col_minutes:>
col_intrep---<:col_intrep:>
col_report---<:col_report:>
col_preprint---<:col_preprint:>
col_course---<:col_course:>
col_bachelor---<:col_bachelor:>
col_diploma---<:col_diploma:>
col_master---<:col_master:>
col_exam---<:col_exam:>
col_magister---<:col_magister:>
col_phd---<:col_phd:>
col_habil---<:col_habil:>
col_talk---<:col_talk:>
col_lecture---<:col_lecture:>
col_poster---<:col_poster:>
col_images---<:col_images:>
col_conf---<:col_conf:>
col_book---<:col_book:>
col_proc---<:col_proc:>
col_contb---<:col_contb:>
col_refs---<:col_refs:>
col_journal---<:col_journal:>
col_contrib---<:col_contrib:>
col_patent---<:col_patent:>
col_abstract---<:col_abstract:>
col_comm---<:col_comm:>
col_formtmp---<:col_formtmp:>
col_news---<:col_news:>
col_notes---<:col_notes:>
col_project---<:col_project:>
col_event---<:col_event:>
col_dataset---<:col_dataset:>
col_sware---<:col_sware:>
col_physobj---<:col_physobj:>
col_media---<:col_media:>



